Mybranch
profedotc/ana_guitierrez pull request #1
Opened 2019-05-17 18:23 UTC by anagutjor

Lo conseguí!!! Ueee

2019-05-18 16:51 UTC, profedotc reviewed
Bueno, en estos primeros commits te comento por encima, porque veo que has ido solucionando los errores poco a poco.

2019-05-18 16:51 UTC, profedotc commented on main.c
> +void gol_copy(bool mundo1, bool mundo2);
El mundo no es de tipo `bool`, sino un array bidemensional de `bool`. Por consiguiente, este es el tipo que deben tener los parámetros de las funciones

2019-05-18 16:51 UTC, profedotc commented on main.c
> +	mundo = false;
Los parámetros son como variables locales de la función, si los modificas, los modificas solo dentro de la función. Además, si `mundo` fuese un array en lugar de un `bool`, esto no estaría inicializando todas las celdas del mundo a `false`, sino modificando la dirección a la que apunta el array por la dirección 0.

2019-05-18 17:02 UTC, profedotc commented on main.c
> +	};
Esto es una forma muy chula de acceder a las coordenadas de las vecinas, pero los índices no parecen estar bien.

2019-05-18 17:02 UTC, profedotc commented on main.c
> +	return mundo[x][y];
Lo que quiero que hagas en esta función es comprobar los límites del array **antes** de acceder a él. Esta función debe permitirnos acceder al array con coordenadas negativas y mayores que el límite, cosa que nos viene muy bien al contar las vecinas.

Cuando detectes que la coordenada que recibes se sale de los límites, puedes elegir la opción que prefieras:
* Devuelves `false`, como si todo lo que estuviese fuera de tu array estuviese muerto.
* Devuelves el valor de la célula del lado opuesto, como si fuese el mundo de pacman (toroidal)

Puedes hacer algo así:
```c
if (x < 0 || x >= TAM_X || y < 0 || y >= TAM_Y)
	return false;
return mundo[x][y];
```

2019-05-18 17:11 UTC, profedotc commented on main.c
> +	}
* Me estás mezclando tabulaciones con espacios. Usa un estilo constante.
* `gol_count_neighbors()` debe devolver el número de células vecinas vivas, nada más. Es en esta función, `gol_step()`, donde debes implementar la lógica que decide si una célula vive o muere.

2019-05-18 17:11 UTC, profedotc commented on main.c
> +		printf("x es %d\n", x + coords[i][0]);
Entiendo que estos `printf` son de depuración. Está muy bien que los uses, pero no que lo subas al repo. En el repositorio quieres tener versiones funcionales de tu programa, no tienen que estar completas, ni libres de bugs, pero sí compilar y funcionar como se espera. Esto elimina de la ecuación cualquier código temporal de prueba o depuración.

2019-05-18 17:11 UTC, profedotc commented on main.c
> +	//printf("mundo es %d\n", mundo[x][y]);
No se suele subir código comentado al repositorio. Simplemente no aporta nada, pero sí ocupa espacio. Date cuenta que esta línea de código ya está en el historial del repositorio, siempre puedes _viajar al pasado_ para recuperarla, no tiene sentido que permanezca comentada.

2019-05-18 17:16 UTC, profedotc requested changes
Este commit de _first_ no tiene nada! xD

Esto ya va teniendo muy buena pinta :) Cámbiame la función `get_cell()` como te he pedido.

2019-05-18 17:16 UTC, profedotc commented on main.c
> +		}
Mueve esta lógica de comprobación de los límites del array a `gol_get_cell()`, verás como te queda todo mucho más sencillo.

Y ten cuidado con la indentación. Aquí es muy difícil ver qué parte del código está dentro del bloque del `if`

2019-05-18 17:16 UTC, profedotc commented on main.c
> +	}
indentación

2019-05-18 20:05 UTC, anagutjor commented on main.c
> +		}
Hola. Sí, no es para nada first, es que como pasó tanto tiempo desde el último commit antes que éste, ya se me había olvidado xD
Bueno, entonces los cambios que tengo que hacer son estos últimos, no? lo de gol_get_cell(), la indentación y quitar los comentarios con los prinf, me equivoco? No sé hacerlo aquí directamente, o si no miro cómo es ya mañana.
Gracias por la pedazo de corrección!

2019-05-19 08:26 UTC, profedotc commented on main.c
> +		}
Sí. Esta función quedaría algo así:
```c
for (int i = 0; i < 8; i++)
	count += gol_get_cell(x + coords[i][0], y + coords[i][1]);
return count;

2019-05-21 18:33 UTC, profedotc commented
Perfecto! Hago merge.

Ya te pediré que muevas ese array de coordenadas (`const int coords[8][2]`), pero antes tengo que explicar algunas cosillas más.

2019-05-21 18:34 UTC, profedotc approved these changes

2019-05-21 18:34 UTC, merged