Tarea 2
profedotc/ana_guitierrez pull request #2
Opened 2019-05-29 17:24 UTC by anagutjor

Carlos, he visto las clases por vídeo y he sacado la tarea 2 pa'lante. Esta semana también ando liada. Volveré la semana que viene.

2019-06-01 17:50 UTC, profedotc requested changes
Muy bien. Sólo arregla el makefile y añade el **.gitignore**

2019-06-01 17:50 UTC, profedotc commented on Makefile
> +	rm main.o gol.o exec
* Los objetivos `main` y `gol` deberían ser `main.o` y `gol.o`: Tu no estás generando ningún archivo que se llame `main` ni `gol`, estás generando los `.o`
* El objetivo `clean` no debe depender de nada. Si depende de `exec`, va a generarlo siempre antes de borrarlo
* Te falta el objetivo que genere el `exec` y ponerlo como dependencia de `all`
```makefile
all: exec
exec: main.o gol.o
	gcc main.o gol.o -o exec
```
* Te falta el objetivo `.PHONY` para identificar los objetivos "especiales", que no van a generar ningún archivo:
```makefile
.PHONY: all clean
```

2019-06-02 10:13 UTC, anagutjor commented on Makefile
> +	rm main.o gol.o exec
Lo acabo de pushear ;)

2019-06-04 18:43 UTC, profedotc approved these changes
hago merge

2019-06-04 18:43 UTC, profedotc commented on Makefile
> +main.o: main.c
`main.o`: depende también de `gol.h` Tu incluyes `gol.h` en `main.c` ¿verdad?

2019-06-04 18:43 UTC, merged

2019-06-05 20:10 UTC, anagutjor commented on Makefile
> +main.o: main.c
ups, es verdad. Sin embargo me sigue compilando bien. Qué cambia al incluir gol.h ahí en el makefile?

2019-06-08 12:27 UTC, profedotc commented on Makefile
> +main.o: main.c
Te compila igual porque la instrucción que tu has escrito para generar el `main.o` es la misma en ambos casos: `gcc -c main.c`
La única diferencia es que, si incluyes `gol.h` en la lista de dependencias, el archivo `main.o` se recompilará si `gol.h` cambia.