Mybranch
profedotc/ana_guitierrez pull request #4
Opened 2019-06-11 11:04 UTC by anagutjor

Gracias por la aclaración de ayer! Ya conseguí sacar la 4.2 :dancer:

2019-06-17 20:18 UTC, profedotc requested changes
Fallos:
* El juego no funciona
* Tiene un doble free
* Tiene leaks

Consejos:
* No uses un tamaño del mundo cuadrado. Esto es muy importante para detectar fallos
* Usa valgrind para comprobar leaks y violaciones de memoria: `valgrind --leaks-check=full ./exec`
* Si tu programa termina con `double free or corruption`, algo hay mal, no pases del tema. Cierra tu programa pulsando `q`, no `Ctrl-C`.

2019-06-17 20:18 UTC, profedotc commented on gol.c
> +	other = 1
Los nombres de los enumerados se ponen en mayúscula, como las macros.
```
enum world_type { CURRENT, OTHER };

2019-06-17 20:18 UTC, profedotc commented on gol.c
> +
Tienes que guardar el tamaño en atributos de tu objeto

2019-06-17 20:18 UTC, profedotc commented on gol.c
> +	for ( int i = 0; i < TAM_X; i++) {
Ya no debes usar las macros aquí, el tamaño de tu mundo es dinámico, debes usar los atributos que hayas guardado en tu objeto

2019-06-17 20:18 UTC, profedotc commented on gol.c
> +	g->worlds[other] = g->worlds[current];
Necesitas un puntero intermedio.

Aquí asignas el mundo actual, `current` al siguiente, `other`, machacando la dirección de memoria que tienes en `other`. ¿Ahora qué? ¿Dónde está tu otro mundo? Ya no lo puedes saber, has perdido la dirección. Tienes un leak y tu programa no funciona.

2019-06-17 20:18 UTC, profedotc commented on gol.h
> +  bool **worlds[2];
Tienes que añadir atributos para guardar el tamaño de esos mundos. Ahora se reserva dinámicamente, y el tamaño no siempre va a ser conocido en tiempo de compilación.
```c
struct gol {
    bool **world[2];
    int size_x;
    int size_y;
};
```

Además, las macros `TAM_X` y `TAM_Y` ya no tienen sentido aquí. Si tu mundo es de tamaño variable, ¿qué son `TAM_X` y `TAM_Y`? Estas macros deben estar en el `main()`, tu librería de gol no tiene un tamaño fijo para el mundo, ni un tamaño por defecto.

2019-06-17 20:18 UTC, profedotc commented on main.c
> +	gol_free(&g, TAM_X);
¿Ves? Esto queda suuper raro. ¿Por qué le tengo que pasar el número de filas a `gol_free()`? El destructor de nuestro objeto debería saber destruirlo sin ninguna información extra. ¿cómo lo hacemos? Añadiendo el tamaño del array como campos de la estructura `struct gol`.

2019-06-17 20:18 UTC, profedotc commented on gol.c
> +	for (int i = 0; i < y; i++) {
Esto está mal, no es `y`, es `x`. Te has reservado un vector de `x` punteros a bool y ahora guardas dentro `y` elementos, eso no cuadra.

2019-06-18 20:35 UTC, profedotc requested changes

2019-06-18 20:35 UTC, profedotc commented on main.c
> +	if (!gol_alloc(&g, 3, 3)) {
Aquí tienes un leak. Estás reservando dos veces el mundo, borra el `gol_alloc()` de la línea 11

2019-06-18 20:35 UTC, profedotc commented on gol.c
> +	for (int i = 0; i < g->size_x; i++) {
Aquí estás usando `g->size_x` sin inicializar

2019-06-18 20:35 UTC, profedotc commented on gol.c
> +	free(g->worlds[CURRENT]);
No estás liberando `g->world[OTHER]`. Si pasas valgrind verás estos errores

2019-06-18 20:35 UTC, profedotc commented on main.c
> +	if (!gol_alloc(&g, 3, 3)) {
Haz tus pruebas con un mundo de 10x15

2019-06-18 20:59 UTC, anagutjor commented on gol.c
> +	for (int i = 0; i < g->size_x; i++) {
No veas cómo se me ha ido no? :open_mouth:

2019-06-18 21:03 UTC, anagutjor commented on gol.c
> +	free(g->worlds[CURRENT]);
Vale, en el commit de 'tutto buono' le hecho valgring leak-check=full ./exec y no me ha dado ningún error. Creo que ahora sí que sí :trophy:

2019-06-25 19:12 UTC, merged