tarea o subtarea 5.1
profedotc/ana_guitierrez pull request #5
Opened 2019-06-11 13:13 UTC by anagutjor

Marchando! Bueno, en realidad me da un fallo raro en la iteración 8, no sé por qué. Algo de double free. Pero lo que pide la tarea en sí está hecho y funcionando :dancing_women:

2019-06-17 20:55 UTC, profedotc commented
Déjame un comentario aquí cuando arregles la tarea 4

2019-06-19 18:14 UTC, anagutjor commented
Hola. Creo que la tarea 4 ya está arreglada del todo. Ahora mismo comiteo esas correcciones a esta rama también.

2019-06-19 18:16 UTC, anagutjor commented
El problema es que ahora no me va del todo bien. Hace una cosa rara, parpadea. Creo que tiene que ver con el swap pero no lo termino de ver...

2019-06-25 19:30 UTC, profedotc commented
No puedo hacer merge de esta rama :( no has aplicado bien las correcciones de la tarea 4. Seguramente es por eso que esta rama no funciona bien.

Puedes intentar arreglarlo así:
```sh
git checkout mybranch
git merge my-other-branch
git status
# Resolver los conflictos en gol.c
git add gol.c
git commit
git push
```

2019-06-27 10:15 UTC, anagutjor commented
Uy, algo he tocado que la he liado. He resuelto los conflictos manualmente y le he dado a un botón, y ahora quiere mergear los cambios en master... noooo :sob:

2019-06-27 18:08 UTC, profedotc requested changes
Esta es la tarea 5.2 en realidad, aunque ya tienes el `mem_test.c` de la tarea 5.1, pero no funciona.

Arregla el `mem_test.c`

2019-06-27 21:09 UTC, anagutjor commented
Ya está, arreglado el mem_test. Se me olvidó actualizarlo junto con el resto

2019-06-28 17:05 UTC, merged